// Generate board.html — a presentable visual of all issues from live Butterbase data.
// Run: npm run board   (then open board.html)
import { writeFileSync } from "node:fs";
import { selectRows, shutdown } from "./butterbase.ts";

const [issues, deps, phases, teams] = await Promise.all([
  selectRows("issues"), selectRows("dependencies"), selectRows("phases"), selectRows("teams"),
]);
shutdown();

const teamName = (id: number) => teams.find((t: any) => t.id === id)?.name ?? "?";
const byId = new Map(issues.map((i: any) => [i.id, i]));
const blockedBy = (id: number) =>
  deps.filter((d: any) => d.to_issue_id === id && byId.get(d.from_issue_id)?.status !== "done")
      .map((d: any) => byId.get(d.from_issue_id));

const TEAM_COLORS: Record<string, string> = { Design: "#e8a33d", Backend: "#4a7c59", Frontend: "#7d9c43" };
const STATUS: Record<string, string> = { done: "✓ done", in_progress: "● in progress", planned: "○ planned" };

const card = (i: any) => {
  const blockers = blockedBy(i.id);
  const isScope = i.id >= 20;
  return `<div class="card ${i.status}${isScope ? " scope" : ""}">
    <div class="card-top"><span class="iid">#${i.id}</span><span class="team" style="background:${TEAM_COLORS[teamName(i.team_id)] ?? "#999"}">${teamName(i.team_id)}</span></div>
    <div class="title">${i.title}</div>
    <div class="meta">${i.owner ?? ""} · ${STATUS[i.status] ?? i.status} · due ${String(i.committed_date ?? "").slice(0, 10)}</div>
    ${isScope ? `<div class="badge scope-badge">＋ scope change (Jun 5)</div>` : ""}
    ${blockers.length ? `<div class="badge blocked-badge">🚧 blocked by ${blockers.map((b: any) => `#${b.id}`).join(", ")}</div>` : ""}
  </div>`;
};

const col = (p: any) => {
  const inPhase = issues.filter((i: any) => i.phase_id === p.id).sort((a: any, b: any) => a.id - b.id);
  const done = inPhase.filter((i: any) => i.status === "done").length;
  return `<div class="col">
    <h2>${p.name}<span class="count">${done}/${inPhase.length} done</span></h2>
    ${inPhase.map(card).join("\n")}
  </div>`;
};

const html = `<!doctype html><html><head><meta charset="utf-8"><title>BarkPark — Release Board (Meridian)</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; background: #faf6ee; margin: 0; padding: 24px; color: #2d2a24; }
  header { display: flex; align-items: baseline; gap: 16px; margin-bottom: 20px; }
  h1 { margin: 0; font-size: 28px; } h1 .paw { color: #4a7c59; }
  .sub { color: #8a8273; font-size: 14px; }
  .legend { margin-left: auto; font-size: 13px; color: #8a8273; display: flex; gap: 14px; }
  .legend .sw { display: inline-block; width: 11px; height: 11px; border-radius: 3px; margin-right: 4px; vertical-align: -1px; }
  .board { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
  .col h2 { font-size: 16px; border-bottom: 2px solid #e3dccb; padding-bottom: 8px; }
  .col h2 .count { float: right; font-weight: 400; color: #8a8273; font-size: 13px; }
  .card { background: #fff; border-radius: 10px; padding: 12px 14px; margin-bottom: 10px; box-shadow: 0 1px 3px rgba(45,42,36,.12); border-left: 4px solid #d8d2c2; }
  .card.done { opacity: .55; border-left-color: #4a7c59; }
  .card.in_progress { border-left-color: #e8a33d; }
  .card.scope { border-left-color: #2a9d8f; background: #f0faf9; }
  .card-top { display: flex; justify-content: space-between; margin-bottom: 6px; }
  .iid { color: #8a8273; font-size: 13px; font-weight: 600; }
  .team { color: #fff; font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 99px; }
  .title { font-size: 14px; font-weight: 600; line-height: 1.3; }
  .meta { font-size: 12px; color: #8a8273; margin-top: 5px; }
  .badge { display: inline-block; font-size: 11.5px; font-weight: 600; margin-top: 7px; margin-right: 6px; padding: 3px 8px; border-radius: 6px; }
  .scope-badge { background: #2a9d8f; color: #fff; }
  .blocked-badge { background: #fdecea; color: #b3261e; }
</style></head><body>
<header>
  <h1><span class="paw">🐾</span> BarkPark — Release Board</h1>
  <span class="sub">generated by Meridian from live Butterbase data · ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC</span>
  <div class="legend">
    <span><span class="sw" style="background:#e8a33d"></span>Design</span>
    <span><span class="sw" style="background:#4a7c59"></span>Backend</span>
    <span><span class="sw" style="background:#7d9c43"></span>Frontend</span>
    <span><span class="sw" style="background:#2a9d8f"></span>scope change</span>
  </div>
</header>
<div class="board">
${phases.sort((a: any, b: any) => a.sort_order - b.sort_order).map(col).join("\n")}
</div>
</body></html>`;

writeFileSync("board.html", html);
console.log(`board.html written — ${issues.length} issues, ${deps.length} dependencies, ${phases.length} phases.`);
