// Generate board.html — a presentable visual of all issues from live Butterbase data.
// Run: npm run board   (then open board.html)
import { writeFileSync } from "node:fs";
import { selectRows, shutdown } from "./butterbase.ts";

const [issues, deps, phases, teams] = await Promise.all([
  selectRows("issues"), selectRows("dependencies"), selectRows("phases"), selectRows("teams"),
]);
shutdown();

const teamName = (id: number) => teams.find((t: any) => t.id === id)?.name ?? "?";
const byId = new Map(issues.map((i: any) => [i.id, i]));
const blockedBy = (id: number) =>
  deps.filter((d: any) => d.to_issue_id === id && byId.get(d.from_issue_id)?.status !== "done")
      .map((d: any) => byId.get(d.from_issue_id));

const TEAM_COLORS: Record<string, string> = { Design: "#e8a33d", Backend: "#4a7c59", Frontend: "#7d9c43" };
const STATUS: Record<string, string> = { done: "✓ done", in_progress: "● in progress", planned: "○ planned" };

const card = (i: any) => {
  const blockers = blockedBy(i.id);
  const isScope = i.id >= 20;
  return `<div class="card ${i.status}${isScope ? " scope" : ""}">
    <div class="card-top"><span class="iid">#${i.id}</span><span class="team" style="background:${TEAM_COLORS[teamName(i.team_id)] ?? "#999"}">${teamName(i.team_id)}</span></div>
    <div class="title">${i.title}</div>
    <div class="meta">${i.owner ?? ""} · ${STATUS[i.status] ?? i.status} · due ${String(i.committed_date ?? "").slice(0, 10)}</div>
    ${isScope ? `<div class="badge scope-badge">＋ scope change (Jun 5)</div>` : ""}
    ${blockers.length ? `<div class="badge blocked-badge">🚧 blocked by ${blockers.map((b: any) => `#${b.id}`).join(", ")}</div>` : ""}
  </div>`;
};

const col = (p: any) => {
  const inPhase = issues.filter((i: any) => i.phase_id === p.id).sort((a: any, b: any) => a.id - b.id);
  const done = inPhase.filter((i: any) => i.status === "done").length;
  return `<div class="col">
    <h2>${p.name}<span class="count">${done}/${inPhase.length} done</span></h2>
    ${inPhase.map(card).join("\n")}
  </div>`;
};

const html = `<!doctype html><html><head><meta charset="utf-8"><title>BarkPark — Release Board (Meridian)</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; background: #122b1d; margin: 0; padding: 0 28px 28px; color: #eaf3ec; }
  header { display: flex; align-items: center; gap: 22px; padding: 18px 0 16px; }
  header img.art { height: 116px; border-radius: 12px; box-shadow: 0 4px 14px rgba(0,0,0,.4); }
  .wordmark { font-size: 34px; font-weight: 800; letter-spacing: -.5px; }
  .wordmark .bark { color: #fff; } .wordmark .park { color: #6fdc6f; }
  .tagline { color: #9fc5a8; font-size: 14px; margin-top: 3px; }
  .sub { color: #6e9479; font-size: 12.5px; margin-top: 6px; }
  .legend { margin-left: auto; font-size: 13px; color: #9fc5a8; display: flex; gap: 14px; }
  .legend .sw { display: inline-block; width: 11px; height: 11px; border-radius: 3px; margin-right: 4px; vertical-align: -1px; }
  .board { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
  .col h2 { font-size: 16px; color: #eaf3ec; border-bottom: 2px solid #2c4a36; padding-bottom: 8px; }
  .col h2 .count { float: right; font-weight: 400; color: #6e9479; font-size: 13px; }
  .card { background: #f7faf5; border-radius: 10px; padding: 12px 14px; margin-bottom: 10px; box-shadow: 0 2px 6px rgba(0,0,0,.35); border-left: 4px solid #c9d6c4; color: #21301f; }
  .card.done { opacity: .5; border-left-color: #4a7c59; }
  .card.in_progress { border-left-color: #e8a33d; }
  .card.scope { border-left-color: #2a9d8f; background: #e9f7f4; }
  .card-top { display: flex; justify-content: space-between; margin-bottom: 6px; }
  .iid { color: #75806e; font-size: 13px; font-weight: 600; }
  .team { color: #fff; font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 99px; }
  .title { font-size: 14px; font-weight: 600; line-height: 1.3; }
  .meta { font-size: 12px; color: #75806e; margin-top: 5px; }
  .badge { display: inline-block; font-size: 11.5px; font-weight: 600; margin-top: 7px; margin-right: 6px; padding: 3px 8px; border-radius: 6px; }
  .scope-badge { background: #2a9d8f; color: #fff; }
  .blocked-badge { background: #fdecea; color: #b3261e; }
</style></head><body>
<header>
  <img class="art" src="sample-project/BarkPark.png" alt="BarkPark">
  <div>
    <div class="wordmark"><span class="bark">Bark</span><span class="park">Park</span> <span style="color:#9fc5a8;font-weight:400;font-size:20px">— Release Board</span></div>
    <div class="tagline">Find. Connect. Play. Better dog parks. Happier dogs.</div>
    <div class="sub">generated by Meridian from live Butterbase data · ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC</div>
  </div>
  <div class="legend">
    <span><span class="sw" style="background:#e8a33d"></span>Design</span>
    <span><span class="sw" style="background:#4a7c59"></span>Backend</span>
    <span><span class="sw" style="background:#7d9c43"></span>Frontend</span>
    <span><span class="sw" style="background:#2a9d8f"></span>scope change</span>
  </div>
</header>
<div class="board">
${phases.sort((a: any, b: any) => a.sort_order - b.sort_order).map(col).join("\n")}
</div>
</body></html>`;

writeFileSync("board.html", html);
console.log(`board.html written — ${issues.length} issues, ${deps.length} dependencies, ${phases.length} phases.`);
